# The program to run
program: train.py

# Method can be grid, random or bayes
method: random

# Project this sweep is part of
project: fanthom_challenge

# Metric to optimize
metric:
  goal: minimize
  name: validation_loss

# Parameters space to search
parameters:
  model_name:
    values:
      - 'yolos'
      - 'CondDETR'
  learning_rate:
    values:
      - 1e-5
      - 1e-4
      - 1e-3
  training_mode:
    values:
      - 'bbox_classifier'