# The program to run
program: train_yolov8.py

# Method can be grid, random or bayes
method: random

# Project this sweep is part of
project: fanthom_challenge

# Metric to optimize
metric:
  goal: minimize
  name: validation_loss

# Parameters space to search
parameters:
  learning_rate:
    values:
      - 1e-5
      - 1e-4
      - 1e-3
  training_mode:
    values:
      - full
      - detector